version: '3.8'

services:
  backend:
    build: ./backend
    container_name: social-backend
    environment:
      - PORT=5001
      - MONGO_URI=mongodb+srv://harshgovil460:63J7auxCvgkUJrKe@cluster0.b8b6goa.mongodb.net/social-platform?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET_KEY=mysecretkey
      - STREAM_API_KEY=77dh4mq8qrkw
      - STREAM_API_SECRET=s95k2gb3w4bhmkqrex9vp3y3maecyuyn25vrhj2kkk5w8w3wsp6t7fkxucubmscc
    ports:
      - "5001:5001"
    networks:
      - social-network
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=/api
        - VITE_STREAM_API_KEY=77dh4mq8qrkw
    container_name: social-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - social-network
    restart: unless-stopped

networks:
  social-network:
    driver: bridge