services:
  - type: web
    name: social-platform-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: STREAM_API_KEY
        sync: false
      - key: STREAM_API_SECRET
        sync: false